export enum ApiStatus {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
